### ISSUE TITLE
Automated template mirrorlist produces incorrect links

### ISSUE THREAD

**Issue by Spartan322** [Redot-Engine/redot-landing-page#209]
**Issue description:** The template mirrorlist behavior performed by Redot expects `https://www.redotengine.org/api/mirrorlists/4.3.rc.2.json` to produce `https://github.com/Redot-Engine/redot-engine/releases/download/redot-4.3-rc.2/Redot_v4.3-rc.2_export_templates.tpz` as the url however it produces `https://github.com/Redot-Engine/redot-engine/releases/download/redot-4.3.rc.2/Redot_v4.3.rc.2_export_templates.tpz`, notice there is a difference between `redot-4.3-rc.2` and `redot-4.3.rc.2`, Redot releases are in the former style but engine itself points to a link in the latter style. The mirrorlist behavior will need to check for the first occurrence of `<number>.<alpha>` and replace it with `<number>-<alpha>`.

**URL to the web page:** https://www.redotengine.org/api/mirrorlists/4.3.rc.2.json

**Comment by opdev1004** [comment]
If we following former versioning rules, name of json file should be ```4.3-rc.2.json``` as well. Is there any valid reason keeping json file name like ``` 4.3.rc.2.json``` when it actually should be ```4.3-rc.2.json```?

```https://www.redotengine.org/api/mirrorlists/4.3-rc.2.json```

Because it is better to make them same format, instead of using this here and using that there.

mono as well. why do ```.mono.json```? they all need to follow former versioning format, not this here then that there

Do ```https://www.redotengine.org/api/mirrorlists/4.3-rc.2_mono.json```
instead of ```https://www.redotengine.org/api/mirrorlists/4.3.rc.2.mono.json```

This seems invalid. Expecially when they are based on versioning.

**Comment by opdev1004** [comment]
This time, we had enough conversation about this in discord.

The godot engine is really poorly designed. So it's quicker to resolve this issue from web side.

Maybe in the future, if there's a dev who brave and strong enough, he/she/they can change the engine to be better system design.

I will add information about this in the repo.

**Comment by opdev1004** [comment]
#210
