### ISSUE TITLE
`image-compress` should detect only the files that need to be updated

### ISSUE THREAD

**Issue by Spartan322** [Redot-Engine/redot-landing-page#228]
**Issue description:** Adding an image while making articles takes a bit of time and this will only increase as more images are added, if `image-compress` could detect the images only what it needs to change, like by detecting from git only the changed files, this could eliminate this issue.

**Comment by opdev1004** [comment]
maybe next weekend

**Comment by opdev1004** [comment]
I was thinking about this and realized that this feature won't work like github's changed files and the suggested solution is quite invalid.

We can check modified time or check any difference between just copy and pasted files and source files. But we cannot compare between converted files and origin source files because they are already different.

So what we can do is only check if the converted file has same name and it has .avif, .svg, .ico or .gif. And check who's older with modified time.

But that still with the problem that we have to track if any changes that has been made to the files from origin source directory. 

Because checking modified time from both directory and managing them would not cover all the cases that can happen in use case scenario. Like what if both images modified somehow outside of code. And destination image file's modified time is still later than original source.

If we clear and create new one then we only need to care about changes from images from source directory.

Unless someone got better idea this probably better remain as it is.

**Comment by Spartan322** [comment]
You could just query git for files changed in public_images, (whether added, changed, or removed, and it doesn't just have to be public_images, that's just the only relevant case here right now) it already has all the infrastructure to do this and to do it fast, like Godot/Redot does this with a number of things already.

**Comment by opdev1004** [comment]
Okay. We can query changes from .git but is that reliable? like what if someone make mistake and does multiple commit related to /public_images? In that case, how can we find the valid point to compare then grab those changed files for running image compression?

Tracking changes from public_images sounds right though. However, is that really safe from human errors?

Also when is the code execution moment then.

- Before commit, run image compression script manually <- still people can make mistake like multiple commits with  /public_images. Then we may miss some stuffs.
- After commit and automatically commit image compression changes <- double commit for 1 job.

===
In my opinion,

- Someone comes with safe and proper solution.
- Or we remove this image compression later and only take certain image format as a rule. And providing image converting tool with gui for none-programmers.
- Change to CMS with editor that can run image compression on file upload.

**Comment by Spartan322** [comment]
> Okay. We can query changes from .git but is that reliable?

You can query via Git itself and just list all the changed files inside public_images, there are a number of ways to do it but the simplest way to do so is by making a call to Git via the command line interface. (since it has to be installed anyway) Again this is actually what the engine itself already does on a number of occasions.

> like what if someone make mistake and does multiple commit related to /public_images? In that case, how can we find the valid point to compare then grab those changed files for running image compression?

Its not a matter of commits, we already don't run the image-compress on commit anyway, though if you wanted you can do it then, waiting on the compression is needed when messing with said images either way and you can fail the commit and have the commit add the new file which is not staged. Like they can already miss calling image-compress anyway, this wouldn't inherently change that unless you make the commit itself call the compress behavior. We don't need to do anything regarding diffs, Git handles that for us intrinsically, that's why we can even upload any binary files.

> Also when is the code execution moment then.
>
> - Before commit, run image compression script manually <- still people can make mistake like multiple commits with /public_images. Then we may miss some stuffs.
> -  After commit and automatically commit image compression changes <- double commit for 1 job.

If you use Git as an interface, or have anything like [pre-commit](https://pre-commit.com/), it can fail the commit if the file isn't there, adds an unstaged file, and then you can choose to stage it or not, subsequently succeeding cause the file is there and the same as what was spit out. (or alternative it just adds the new/modified file and stages it and then continues the commits itself) As it stands right now we already run into the issue of having to run image compression manually so it doesn't change anything there, you can make it so the script file accepts source and destination files instead of directories and then a pre-commit script that handles the changed the source file and spits it to the destination path, if you do that then not only can you direct it towards only compressing the changed images, but you could run a kind of "image-compress all" command and it'll just do what its currently doing anyway. (or you could script it to allow specifing the file's path or its relative path inside of public_images manually instead)

**Comment by opdev1004** [comment]
Not everyone can check changes and run image compression on each changed file before they make commit. Not everyone is like us. And some people use git with GUI. The solution for this better be level of none-programmer who only can type short command on their terminal or just can button click. Engine side can be your way because there's no none programmer.

Everyone has different level of experience. And we need to be prepared for people who do not know anything about git or even the use of terminal.

So unless you give a solution that none-programmer can do, with very small learning like really really small learning, nothing is solved. You are just making it more complicated.

There are three options for this in my opinion for right now.
- You provide solution that Chimpanzees can do as this repository is not only for developer or software engineer
- You build a solution just for developer/software engineer like just for yourself
- We remove this automation and only push lossy compression image format or small file size image format for web.

**Comment by Spartan322** [comment]
> Not everyone can check changes and run image compression on each changed file before they make commit.

They already have to do it every time they modify something in public_images, you can do it through a pre-commit behavior and it'll just work on every commit automatically when you try to commit, no need for any extra work.

> And some people use git with GUI.

All of them still require Git to be installed, for example Github Desktop will not work without Git being installed, (and its not the only one) and that aside if you run them through pre-commit it already can have access to everything Git knows.

> The solution for this better be level of none-programmer who only can type short command on their terminal or just can button click. Engine side can be your way because there's no none programmer.

That's literally how pre-commit hooks work, you already use them via husky anyway, it does not require any terminal use at all, the engine was doing it automatically without input from the developer, you're already doing it right now, its just quite simplistic what is currently being done because you ignore the changed files that git pre-commit hooks provide for you.

**Comment by opdev1004** [comment]
Man, you got communication problem.

Next time just say use pre-commit hooks instead of all that pointless git lecture.

There's huge difference between just mentioning to use pre-commit hook and all that things you wirte about query git and other git stuffs.

If we use hook, we gotta setup github action as well. Because husky won't work from github website?

**Comment by Spartan322** [comment]
I did mention the python pre-commit [here](https://github.com/Redot-Engine/redot-landing-page/issues/228#issuecomment-2484090047) and then go on further to explain how pre-commit hooks can be used to do all these things. Like could use say https://mookme.org. (or anything similar, there are a number npm git hook packages) And a pre-commit doesn't exactly need to be setup as a Github Action but I don't see why it wouldn't work to validate a result, the scripts just need to be setup to do that.

**Comment by opdev1004** [comment]
Just to be clear, are you sure that husky also runs with github website commit?

**Comment by tindrew** [comment]
Just so I'm understanding this. Right now you have to run image-compress when adding images. I know because I've added a few already. The issue is, image-compress re-compresses all the images in the project, not just the one you just added. What about a tool that you can throw the image into and have it compress and spit out a compressed image, then you throw the compressed one into the project? That might be easier than trying to do all this crazy git stuff. That would save the step of trying to run image-compress every time you add a single image. Or, if there's a way to run image-compress on say, a random folder(I'm showing my ignorance of how it works here)

**Comment by Spartan322** [comment]
Husky itself does not because its only designed to install hooks and has no capacity to perform the pre-commit behavior itself. (least from what I see of the documentation) However something like mookme (and many of the other git hook packages) do give you the ability to run them independent of a commit hook call, like from the command line.

**Comment by Spartan322** [comment]
> Just so I'm understanding this. Right now you have to run image-compress when adding images. I know because I've added a few already. The issue is, image-compress re-compresses all the images in the project, not just the one you just added. What about a tool that you can throw the image into and have it compress and spit out a compressed image, then you throw the compressed one into the project? That might be easier than trying to do all this crazy git stuff. That would save the step of trying to run image-compress every time you add a single image. Or, if there's a way to run image-compress on say, a random folder(I'm showing my ignorance of how it works here)

We already have a pre-commit hook, you can't run `image-compress` without it running first, we don't need a tool, (even that aside the script would be the tool anyway) with a pre-commit hook handling this all you'd need to do is add the image to your local repo, commit it, it would generate the compressed image only for the changed file, (or delete it if its been removed) and then that can be pushed to the repo. That way nobody forgets to compress an image.

**Comment by opdev1004** [comment]
Actually pre commit hook is not really a solution because converted image needs to be there already still.

For preview dev result from local from `npm run dev`.

**Comment by tindrew** [comment]
yeah that's the issue. You can't preview the image without running image-compress when running it locally. That's why I was thinking if there was some tool or something you could compress the image you want to add first, that way you're not running it on every image already in the project too.

**Comment by opdev1004** [comment]
> yeah that's the issue. You can't preview the image without running image-compress when running it locally. That's why I was thinking if there was some tool or something you could compress the image you want to add first, that way you're not running it on every image already in the project too.

That's one thing that I've mentioned above. Providing a image compression tool with GUI.

Like can anyone make one with redot, just convert them to .avif, or I just build and serve a page that provide GUI and do image compression, outside of our main website

**Comment by tindrew** [comment]
Not sure if someone could build one with the engine(cool idea, I could ask the community) but even a page that did it would be fine

**Comment by opdev1004** [comment]
I think I will close this, as we are not going this direction.

We better provide image compression page or app for all user.

**Comment by Spartan322** [comment]
> Actually pre commit hook is not really a solution because converted image needs to be there already still.

What? That's how pre-commit works, what are you talking about?

>  You can't preview the image without running image-compress when running it locally.

pre-commit runs locally, and you could have it fail if the pre-commit script created a new image, which would allow you to review.

**Comment by opdev1004** [comment]
` Husky will run before commit. `
`pre-commit: Runs scripts before a commit is finalized.`

images need to be already in public folder for npm run dev.

**Comment by Spartan322** [comment]
Because its a pre-commit hook on git, I don't understand the issue, you have to install git hooks in order to use them, the alternative is having no pre-commit which is objectively the worse option.

**Comment by opdev1004** [comment]
nah just leave. do your engine. I think that's more clear for you.

**Comment by Spartan322** [comment]
The reason its a concern for me is because us engine maintainers are the ones who would be submitting release articles out of necessity, and every minute saved and streamlined is one less thing to mess up and forget, having one person doing all the release stuff is also much quicker.

**Comment by opdev1004** [comment]
So we saying we are providing a page or app that you can just drag and drop the file for image compression that goes to public folder.

**Comment by Spartan322** [comment]
That's kinda worse then what we currently have right now and it still shares the exact same problems, if anything it actually will take longer to do for a while into the future until image-compress becomes full of a bunch more images.

**Comment by opdev1004** [comment]
nope, your brain is messed up at the moment. So just let us handle this. Don't direct us what to do like you're a boss here.

The reason we are not doing image compression on pre-commit, it still cannot cover all the use cases. It must not be only about use cases that happen in your way and in your brain.

And noone said the new way will compress bunch of images, like all the images. We are just going to maintain compressed images with git. And app/page will be just like drag and drop image that convert and point to public directory. Which won't take long since it only process images that are going to be added.

So just leave it instead of pushing your idea.

**Comment by opdev1004** [comment]
> yeah that's the issue. You can't preview the image without running image-compress when running it locally. That's why I was thinking if there was some tool or something you could compress the image you want to add first, that way you're not running it on every image already in the project too.

I will quote what drew said so you can understand the context. I think you gotta have some rest. Stop pushing yourself too much.

And when he say cannot preview, it means we cannot preview any changes with 'npm run dev' with checking website with local server. We can check only after the commit and that's not a good development and maintenance process because that can create more commits.
